FORMAT: 1A
HOST: https://my-diary-app-np.herokuapp.com/api/v1

# mydiaryapp

My Diary app api allows users create an account, login, add, view and modify diary entries.


## Create user account [/auth/signup]

### Signup [POST]
You may create your own user account using this action. It takes a JSON
object containing a username, password and email address.

+ Request (application/json)

            {
                "username" : "username",
                "password" : "password",
                "email_address" : "example@gmail.com"
            }

+ Response 400 (application/json)

            {
                "message" : "Please provide a username"
            }
            
+ Response 400 (application/json)

            {
                "message" : "Please provide an email address"
            }

+ Response 400 (application/json)

            {
                "message" : "Please provide a valid email address"
            }

+ Response 201 (application/json)

            {
                "message" : "User successfully signed up"
            }

+ Response 409 (application/json)

            {
                "message" : "message": "User already exists. Please log in"
            }

## Log into user account [/auth/login]

### Login [POST]

You may login using this action. It takes a JSON
object containing a username, password and email_address.

+ Request (application/json)

            {
                "username" : "username",
                "password" : "password",
                "email_address" : "example@gmail.com"
            }

+ Response 200 (application/json)

            {
                "message": "You have successfully logged in"
            }

## Entries collection [/entries]

### Add entry [POST]

You may add a diary entry using this action. It requires an access token in the headers.
It takes in a JSON object containing a title and details

+ Request (application/json)

    + Headers 
    
            access-token:token
            
    + Body

            {
                "title": "My title",
                "details": "My details"
            }

        
+ Response 403 (application/json)

        {
            "message" : "Token is missing"
        }
        
+ Response 403 (application/json)

        {
            "message" : "Signature expired. Please log in again."
        }

+ Response 201 (application/json)

        {
            "message": "Entry successfully added"
        }
        
### View all entries [GET]

You may view all your diary entries using this action. It requires an access token in the headers.

+ Request (application/json)

    + Headers
            
            access-token:token
            

+ Response 200 (application/json)

        {
            "message" : "All entries successfully retrieved"
        }
        
## Individual entry collection [/entries/<entryId>]

### Get an entry by entryId [POST]

You may get an entry by entryId with this action. It requires an access token in the headers.


+ Request (application/json)

    + Headers 
    
            access-token:token
            
+ Response 200 (application/json)

        {
            "message": "Entry successfully retrieved"
        }
+ Response 404 (application/json)

        {
            "message": "Entry does not exist. Try again"
        }